#!/usr/bin/env python
# -*- encoding : utf-8 -*-
import sys, os, subprocess, random
commit_msg_filepath = sys.argv[1]
# Got sick of seeing my commits that just fix tests, now they come with fun emoticons
# Frustrated emoticons (ノಠ益ಠ)ノ彡┻━┻
emoticonList = ["(ノಠ益ಠ)ノ彡┻━┻", "ಠ_ಠ", "┬─┬ノ( º _ ºノ)", "(╯°□°）╯︵ ┻━┻"]
# List of key words where it mentions fixing tests!
fixTestsList = ['fix test', 'fix build', 'build fix', 'broken test', 'fixing test', 'test fixes', 'fixed']
with open(commit_msg_filepath, 'r+') as f:
     content = f.read()
     containsFixTests = any(substring in content for substring in fixTestsList)
     if(containsFixTests):
         f.write(random.choice(emoticonList))
