#!/usr/bin/env python
import sys, os, subprocess, random
commit_msg_filepath = sys.argv[1]
# Table flip emoticons for when fixing test (ノಠ益ಠ)ノ彡┻━┻
emoticonList = ["(ノಠ益ಠ)ノ彡┻━┻", "ಠ_ಠ", "┬─┬ノ( º _ ºノ)", "(╯°□°）╯︵ ┻━┻"]
# List of key words where it mentions fixing tests!
fixTestsList = ['fix test', 'fix build', 'build fix', 'broken test', '...']
with open(commit_msg_filepath, 'r+') as f:
     content = f.read()
     containsFixTests = any(substring in content for substring in fixTestsList)
     if(containsFixTests):
         f.write(random.choice(emoticonList))
