#!/usr/bin/env python
import sys, os
import subprocess
commit_msg_filepath = sys.argv[1]
isInitialCommit = subprocess.Popen(["git", "rev-parse", "--verify", "HEAD", ">/dev/null", "2>&1"], stdout=subprocess.PIPE).communicate()[0]

if not isInitialCommit:
    with open(commit_msg_filepath, 'w') as f:
        f.write("# Please include a useful commit message!")
